apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobrunner
spec:
  selector:
    matchLabels:
      app: jobrunner
  template:
    metadata:
      labels:
        app: jobrunner
    spec:
      containers:
      - name: jobrunner
        image: starcitizentools/mediawiki:jobrunner-v0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: PRD_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prd-db-password
              key: db_password